"""
rf_engine/harmonics.py
──────────────────────
Harmonic product calculator.

A harmonic of order n generated by a fundamental f is:
    H_n = n × f

These are the simplest and most common cause of aeronautical interference
(e.g. a 3rd harmonic of a 39.667 MHz oscillator landing on 119.000 MHz).
"""

from __future__ import annotations
from dataclasses import dataclass

from .tolerance import ToleranceResult, check_tolerance


@dataclass(slots=True)
class HarmonicProduct:
    """One harmonic product candidate."""
    order: int
    source_mhz: float
    result_mhz: float
    formula: str
    tipo: str              # "H2", "H3", …
    tolerance: ToleranceResult


def calculate_harmonics(
    freq_mhz: float,
    target_mhz: float,
    tolerance_khz: float,
    max_order: int = 5,
) -> list[HarmonicProduct]:
    """
    Calculate harmonics of ``freq_mhz`` up to ``max_order`` and check each
    against ``target_mhz`` within ``tolerance_khz``.

    Args:
        freq_mhz:      Fundamental frequency of the emitter in MHz.
        target_mhz:    Affected aeronautical frequency in MHz.
        tolerance_khz: Maximum allowed error in kHz.
        max_order:     Highest harmonic order to evaluate (default 5).

    Returns:
        List of HarmonicProduct only for orders that match within tolerance.

    Example:
        # 3rd harmonic of 39.667 MHz ≈ 119.001 MHz → match within 10 kHz
        >>> results = calculate_harmonics(39.667, 119.000, 10)
        >>> results[0].tipo     # "H3"
        >>> results[0].formula  # "3 × 39.667"
    """
    matches: list[HarmonicProduct] = []

    for n in range(2, max_order + 1):
        result = round(n * freq_mhz, 9)
        tol = check_tolerance(result, target_mhz, tolerance_khz)

        if tol.match:
            matches.append(
                HarmonicProduct(
                    order=n,
                    source_mhz=freq_mhz,
                    result_mhz=result,
                    formula=f"{n} × {freq_mhz}",
                    tipo=f"H{n}",
                    tolerance=tol,
                )
            )

    return matches


def all_harmonics_table(freq_mhz: float, max_order: int = 6) -> list[dict]:
    """
    Return a table of all harmonics up to max_order (no tolerance filter).
    Useful for the GET /rf/harmonics/{freq} informational endpoint.
    """
    return [
        {
            "order":      n,
            "freq_mhz":   round(n * freq_mhz, 6),
            "formula":    f"{n} × {freq_mhz}",
            "tipo":       f"H{n}",
        }
        for n in range(2, max_order + 1)
    ]
